name: dependent jobs
on: push
jobs:
 job_on_ubuntu:
  runs-on: ubuntu-latest
  steps:
  - run: date
 job_on_windows:
  name: a Windows job
  runs-on: windows-latest
  steps:
  - name: first step in windows job
    run: date
 job_on_macos:
  needs: [job_on_ubuntu, job_on_windows]
  name: a job that runs on macos
  runs-on: macos-latest
  steps:
  - run: pwd
  - name: new step 
    run: ls
  - name: new step2
    run: ps -aux
 Final_job:
  needs: job_on_macos
  runs-on: ubuntu-latest
  name: a final job
  steps:
  - run: echo Hello World!
